test win ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -389,14 +389,14 @@ jobs:
 #    - name: Build WebGL Efficientnet
 #      run: WEBGL=1 python -m examples.compile_efficientnet
 
-  tests:
+  testwin:
     strategy:
       fail-fast: false
       matrix:
-        backend: [llvm, clang, gpu, ptx, amd, nv] #, triton]
+        backend: [gpu]
 
-    name: Tests on (${{ matrix.backend }})
-    runs-on: ubuntu-22.04
+    name: Tests on (${{ matrix.backend }}) (win)
+    runs-on: windows-latest
     timeout-minutes: 20
 
     steps:
@@ -423,127 +423,168 @@ jobs:
       - name: Install OpenCL
         if: matrix.backend == 'gpu'
         run: |
-          echo 'Acquire::http::Pipeline-Depth "5";' | sudo tee -a /etc/apt/apt.conf.d/99parallel
-          echo "deb [ allow-insecure=yes ] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
-          sudo apt update || true
-          sudo apt install --allow-unauthenticated -y --no-install-recommends opencl-headers \
-            intel-oneapi-runtime-openmp=2023.2.1-16 intel-oneapi-runtime-compilers-common=2023.2.1-16 intel-oneapi-runtime-compilers=2023.2.1-16 \
-            intel-oneapi-runtime-dpcpp-sycl-opencl-cpu=2023.2.1-16 intel-oneapi-runtime-tbb-common=2021.10.0-49541 \
-            intel-oneapi-runtime-tbb=2021.10.0-49541 intel-oneapi-runtime-opencl=2023.2.1-16
-      - name: Install packages (cuda)
-        if: matrix.backend == 'ptx' || matrix.backend == 'triton' || matrix.backend == 'nv'
-        run: |
-          echo 'Acquire::http::Pipeline-Depth "5";' | sudo tee -a /etc/apt/apt.conf.d/99parallel
-          sudo apt update -y || true
-          sudo apt install -y --no-install-recommends git g++ cmake ninja-build llvm-15-dev zlib1g-dev libglew-dev \
-            flex bison libfl-dev libboost-thread-dev libboost-filesystem-dev nvidia-cuda-toolkit-gcc libzstd-dev
-      - name: Cache gpuocelot
-        if: matrix.backend == 'ptx' || matrix.backend == 'triton' || matrix.backend == 'nv'
-        id: cache-build
-        uses: actions/cache@v4
-        env:
-          cache-name: cache-gpuocelot-build
-        with:
-          path: ${{ github.workspace }}/gpuocelot/ocelot
-          key: ubuntu22.04-gpuocelot-4524e34adb7eaccc6f71262f2e21d7052bb17c2f-rebuild-8
-      - name: Clone/compile gpuocelot
-        if: (matrix.backend == 'ptx' || matrix.backend == 'triton' || matrix.backend == 'nv') && steps.cache-build.outputs.cache-hit != 'true'
-        run: |
-          git clone --recurse-submodules https://github.com/gpuocelot/gpuocelot.git ${{ github.workspace }}/gpuocelot
-          cd ${{ github.workspace }}/gpuocelot/ocelot
-          git checkout 4524e34adb7eaccc6f71262f2e21d7052bb17c2f
-          mkdir build
-          cd build
-          cmake .. -Wno-dev -G Ninja -DOCELOT_BUILD_TOOLS=OFF -DCMAKE_BUILD_ALWAYS=0 -DBUILD_TESTS_CUDA=OFF
-          ninja
-      - name: Install gpuocelot
-        if: matrix.backend == 'ptx' || matrix.backend == 'triton' || matrix.backend == 'nv'
-        run: |
-          cd ${{ github.workspace }}/gpuocelot/ocelot/build
-          sudo ninja install -d explain
-      - name: Install packages (amd)
-        if: matrix.backend == 'amd'
-        run: |
-          echo 'Acquire::http::Pipeline-Depth "5";' | sudo tee -a /etc/apt/apt.conf.d/99parallel
-          wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | sudo tee /etc/apt/keyrings/rocm.gpg > /dev/null
-          sudo tee /etc/apt/sources.list.d/rocm.list <<'EOF'
-          deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.1.2 jammy main
-          EOF
-          echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600
-          sudo apt update || true
-          sudo apt install --no-install-recommends --allow-unauthenticated -y hsa-rocr comgr hsa-rocr-dev liburing-dev libc6-dev
-          curl -s https://api.github.com/repos/Qazalin/remu/releases/latest | \
-          jq -r '.assets[] | select(.name == "libremu.so").browser_download_url' | \
-          sudo xargs curl -L -o /usr/local/lib/libremu.so
-          sudo tee --append /etc/ld.so.conf.d/rocm.conf <<'EOF'
-            /opt/rocm/lib
-            /opt/rocm/lib64
-          EOF
-          sudo ldconfig
-      - name: Install dependencies
-        run: pip install -e '.[testing${{matrix.backend=='llvm'&&',llvm'||matrix.backend=='ptx'&&',cuda'||matrix.backend=='triton'&&',triton'||''}}]' --extra-index-url https://download.pytorch.org/whl/cpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/
-      - name: Check Device.DEFAULT and print some source
-        run: |
-          PYTHONPATH=${{ github.workspace }} python3 -c "from tinygrad import Device; assert Device.DEFAULT in ['LLVM','CLANG','CUDA','GPU','AMD','NV'], Device.DEFAULT"
-          DEBUG=5 PYTHONPATH=${{ github.workspace }} FORWARD_ONLY=1 python3 test/test_ops.py TestOps.test_add
-      - name: Verify OpenCL autogen
-        if: matrix.backend == 'gpu'
-        run: |
-          cp tinygrad/runtime/autogen/opencl.py /tmp/opencl.py.bak
-          ./autogen_stubs.sh opencl
-          diff /tmp/opencl.py.bak tinygrad/runtime/autogen/opencl.py
-      - name: Verify CUDA autogen
-        if: matrix.backend == 'nv'
-        run: |
-          cp tinygrad/runtime/autogen/cuda.py /tmp/cuda.py.bak
-          cp tinygrad/runtime/autogen/nv_gpu.py /tmp/nv_gpu.py.bak
-          ./autogen_stubs.sh cuda
-          ./autogen_stubs.sh nv
-          diff /tmp/cuda.py.bak tinygrad/runtime/autogen/cuda.py
-          diff /tmp/nv_gpu.py.bak tinygrad/runtime/autogen/nv_gpu.py
-      - name: Verify AMD autogen
-        if: matrix.backend == 'amd'
-        run: |
-          cp tinygrad/runtime/autogen/hsa.py /tmp/hsa.py.bak
-          cp tinygrad/runtime/autogen/comgr.py /tmp/comgr.py.bak
-          cp tinygrad/runtime/autogen/amd_gpu.py /tmp/amd_gpu.py.bak
-          ./autogen_stubs.sh hsa
-          ./autogen_stubs.sh comgr
-          ./autogen_stubs.sh amd
-          diff /tmp/hsa.py.bak tinygrad/runtime/autogen/hsa.py
-          diff /tmp/comgr.py.bak tinygrad/runtime/autogen/comgr.py
-          diff /tmp/amd_gpu.py.bak tinygrad/runtime/autogen/amd_gpu.py
-      - name: Verify Linux autogen
-        if: matrix.backend == 'amd'
-        run: |
-          cp tinygrad/runtime/autogen/libc.py /tmp/libc.py.bak
-          cp tinygrad/runtime/autogen/io_uring.py /tmp/io_uring.py.bak
-          ./autogen_stubs.sh libc
-          ./autogen_stubs.sh io_uring
-          diff /tmp/libc.py.bak tinygrad/runtime/autogen/libc.py
-          diff /tmp/io_uring.py.bak tinygrad/runtime/autogen/io_uring.py
-      - name: Run pytest (not cuda or amd)
-        if: matrix.backend!='ptx' && matrix.backend!='triton' && matrix.backend != 'amd' && matrix.backend != 'nv'
-        run: python -m pytest -n=auto test/ --ignore=test/unit --durations=20
-      # - name: Run test_ops with FUZZ_UOPS=1
-      #   if: matrix.backend!='cuda' && matrix.backend!='ptx' && matrix.backend!='triton' && matrix.backend != 'amd' && matrix.backend != 'nv'
-      #   run: FUZZ_UOPS=1 python -m pytest -n=auto test/test_ops.py --durations=20
-      - name: Run ONNX (only LLVM)
-        if: matrix.backend == 'llvm'
-        run: python -m pytest -n=auto test/external/external_test_onnx_backend.py --durations=20
-      - name: Run pytest (cuda)
-        if: matrix.backend=='ptx'||matrix.backend=='triton'||matrix.backend=='nv'
-        run: python -m pytest -n=auto test/ -k 'not (half or test_efficientnet_safetensors)' --ignore=test/external --ignore=test/models --ignore=test/unit --ignore test/test_gc.py --durations=20
-      - name: Run pytest (amd)
-        if: matrix.backend=='amd'
-        run: python -m pytest -n=auto test/test_ops.py test/test_dtype.py test/test_dtype_alu.py test/test_linearizer.py test/test_randomness.py test/imported/test_indexing.py test/test_hcq.py --durations=20
-      - name: Run TRANSCENDENTAL math
-        run: TRANSCENDENTAL=2 python -m pytest -n=auto test/test_ops.py::TestOps::test_sin test/test_ops.py::TestOps::test_cos test/test_ops.py::TestOps::test_tan test/test_ops.py::TestOps::test_exp test/test_ops.py::TestOps::test_log --durations=20
-      - name: Run process replay tests
-        run: |
-          export PR_TITLE=$(jq -r .pull_request.title "$GITHUB_EVENT_PATH")
-          export COMMIT_MESSAGE=$(git show -s --format=%B ${{ github.event.pull_request.head.sha }})
-          cp test/external/process_replay/process_replay.py ./process_replay.py && git fetch origin master && git -c advice.detachedHead=false checkout origin/master && PYTHONPATH=. python3 process_replay.py
+          $ProgressPreference = 'SilentlyContinue'
+          Invoke-WebRequest -Uri "https://github.com/intel/compute-runtime/releases/download/21.49.21786/intel-opencl-icd-21.49.21786-release-x64.zip" -OutFile "opencl-runtime.zip"
+          Expand-Archive -Path "opencl-runtime.zip" -DestinationPath "C:\Intel"
+          $env:Path += ";C:\Intel\Intel(R) OpenCL"
+          [Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)
+          clinfo
+
+  # tests:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       backend: [llvm, clang, gpu, ptx, amd, nv] #, triton]
+
+  #   name: Tests on (${{ matrix.backend }})
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 20
+
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 2 # NOTE: this fetches the HEAD commit of the PR
+  #     - name: Set up Python 3.11
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: 3.11
+  #     - name: Cache python packages
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ${{ env.Python3_ROOT_DIR }}/lib/python3.11/site-packages
+  #         key: ${{ matrix.backend }}-packages-${{ hashFiles('**/setup.py') }}
+  #     - name: Cache downloads
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.cache/tinygrad/downloads/
+  #         key: downloads-cache-${{ matrix.backend }}-${{ env.DOWNLOAD_CACHE_VERSION }}
+  #     - name: Set env
+  #       run: printf "${{ matrix.backend == 'llvm' && 'LLVM=1' || matrix.backend == 'clang' && 'CLANG=1' || matrix.backend == 'gpu' && 'GPU=1' || matrix.backend == 'PTX' && 'FORWARD_ONLY=1\nJIT=1\nOPT=2\nNV=1\nPTX=1\nMOCKGPU=1' || matrix.backend == 'triton' && 'FORWARD_ONLY=1\nJIT=1\nOPT=2\nNV=1\nMOCKGPU=1\nTRITON=1\nTRITON_PTXAS_PATH=/usr/bin/ptxas' || matrix.backend == 'amd' && 'AMD=1\nMOCKGPU=1\nFORWARD_ONLY=1' || matrix.backend == 'nv' && 'NV=1\nMOCKGPU=1\nFORWARD_ONLY=1' }}" >> $GITHUB_ENV
+  #     - name: Install OpenCL
+  #       if: matrix.backend == 'gpu'
+  #       run: |
+  #         echo 'Acquire::http::Pipeline-Depth "5";' | sudo tee -a /etc/apt/apt.conf.d/99parallel
+  #         echo "deb [ allow-insecure=yes ] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
+  #         sudo apt update || true
+  #         sudo apt install --allow-unauthenticated -y --no-install-recommends opencl-headers \
+  #           intel-oneapi-runtime-openmp=2023.2.1-16 intel-oneapi-runtime-compilers-common=2023.2.1-16 intel-oneapi-runtime-compilers=2023.2.1-16 \
+  #           intel-oneapi-runtime-dpcpp-sycl-opencl-cpu=2023.2.1-16 intel-oneapi-runtime-tbb-common=2021.10.0-49541 \
+  #           intel-oneapi-runtime-tbb=2021.10.0-49541 intel-oneapi-runtime-opencl=2023.2.1-16
+  #     - name: Install packages (cuda)
+  #       if: matrix.backend == 'ptx' || matrix.backend == 'triton' || matrix.backend == 'nv'
+  #       run: |
+  #         echo 'Acquire::http::Pipeline-Depth "5";' | sudo tee -a /etc/apt/apt.conf.d/99parallel
+  #         sudo apt update -y || true
+  #         sudo apt install -y --no-install-recommends git g++ cmake ninja-build llvm-15-dev zlib1g-dev libglew-dev \
+  #           flex bison libfl-dev libboost-thread-dev libboost-filesystem-dev nvidia-cuda-toolkit-gcc libzstd-dev
+  #     - name: Cache gpuocelot
+  #       if: matrix.backend == 'ptx' || matrix.backend == 'triton' || matrix.backend == 'nv'
+  #       id: cache-build
+  #       uses: actions/cache@v4
+  #       env:
+  #         cache-name: cache-gpuocelot-build
+  #       with:
+  #         path: ${{ github.workspace }}/gpuocelot/ocelot
+  #         key: ubuntu22.04-gpuocelot-4524e34adb7eaccc6f71262f2e21d7052bb17c2f-rebuild-8
+  #     - name: Clone/compile gpuocelot
+  #       if: (matrix.backend == 'ptx' || matrix.backend == 'triton' || matrix.backend == 'nv') && steps.cache-build.outputs.cache-hit != 'true'
+  #       run: |
+  #         git clone --recurse-submodules https://github.com/gpuocelot/gpuocelot.git ${{ github.workspace }}/gpuocelot
+  #         cd ${{ github.workspace }}/gpuocelot/ocelot
+  #         git checkout 4524e34adb7eaccc6f71262f2e21d7052bb17c2f
+  #         mkdir build
+  #         cd build
+  #         cmake .. -Wno-dev -G Ninja -DOCELOT_BUILD_TOOLS=OFF -DCMAKE_BUILD_ALWAYS=0 -DBUILD_TESTS_CUDA=OFF
+  #         ninja
+  #     - name: Install gpuocelot
+  #       if: matrix.backend == 'ptx' || matrix.backend == 'triton' || matrix.backend == 'nv'
+  #       run: |
+  #         cd ${{ github.workspace }}/gpuocelot/ocelot/build
+  #         sudo ninja install -d explain
+  #     - name: Install packages (amd)
+  #       if: matrix.backend == 'amd'
+  #       run: |
+  #         echo 'Acquire::http::Pipeline-Depth "5";' | sudo tee -a /etc/apt/apt.conf.d/99parallel
+  #         wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | sudo tee /etc/apt/keyrings/rocm.gpg > /dev/null
+  #         sudo tee /etc/apt/sources.list.d/rocm.list <<'EOF'
+  #         deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.1.2 jammy main
+  #         EOF
+  #         echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600
+  #         sudo apt update || true
+  #         sudo apt install --no-install-recommends --allow-unauthenticated -y hsa-rocr comgr hsa-rocr-dev liburing-dev libc6-dev
+  #         curl -s https://api.github.com/repos/Qazalin/remu/releases/latest | \
+  #         jq -r '.assets[] | select(.name == "libremu.so").browser_download_url' | \
+  #         sudo xargs curl -L -o /usr/local/lib/libremu.so
+  #         sudo tee --append /etc/ld.so.conf.d/rocm.conf <<'EOF'
+  #           /opt/rocm/lib
+  #           /opt/rocm/lib64
+  #         EOF
+  #         sudo ldconfig
+  #     - name: Install dependencies
+  #       run: pip install -e '.[testing${{matrix.backend=='llvm'&&',llvm'||matrix.backend=='ptx'&&',cuda'||matrix.backend=='triton'&&',triton'||''}}]' --extra-index-url https://download.pytorch.org/whl/cpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/
+  #     - name: Check Device.DEFAULT and print some source
+  #       run: |
+  #         PYTHONPATH=${{ github.workspace }} python3 -c "from tinygrad import Device; assert Device.DEFAULT in ['LLVM','CLANG','CUDA','GPU','AMD','NV'], Device.DEFAULT"
+  #         DEBUG=5 PYTHONPATH=${{ github.workspace }} FORWARD_ONLY=1 python3 test/test_ops.py TestOps.test_add
+  #     - name: Verify OpenCL autogen
+  #       if: matrix.backend == 'gpu'
+  #       run: |
+  #         cp tinygrad/runtime/autogen/opencl.py /tmp/opencl.py.bak
+  #         ./autogen_stubs.sh opencl
+  #         diff /tmp/opencl.py.bak tinygrad/runtime/autogen/opencl.py
+  #     - name: Verify CUDA autogen
+  #       if: matrix.backend == 'nv'
+  #       run: |
+  #         cp tinygrad/runtime/autogen/cuda.py /tmp/cuda.py.bak
+  #         cp tinygrad/runtime/autogen/nv_gpu.py /tmp/nv_gpu.py.bak
+  #         ./autogen_stubs.sh cuda
+  #         ./autogen_stubs.sh nv
+  #         diff /tmp/cuda.py.bak tinygrad/runtime/autogen/cuda.py
+  #         diff /tmp/nv_gpu.py.bak tinygrad/runtime/autogen/nv_gpu.py
+  #     - name: Verify AMD autogen
+  #       if: matrix.backend == 'amd'
+  #       run: |
+  #         cp tinygrad/runtime/autogen/hsa.py /tmp/hsa.py.bak
+  #         cp tinygrad/runtime/autogen/comgr.py /tmp/comgr.py.bak
+  #         cp tinygrad/runtime/autogen/amd_gpu.py /tmp/amd_gpu.py.bak
+  #         ./autogen_stubs.sh hsa
+  #         ./autogen_stubs.sh comgr
+  #         ./autogen_stubs.sh amd
+  #         diff /tmp/hsa.py.bak tinygrad/runtime/autogen/hsa.py
+  #         diff /tmp/comgr.py.bak tinygrad/runtime/autogen/comgr.py
+  #         diff /tmp/amd_gpu.py.bak tinygrad/runtime/autogen/amd_gpu.py
+  #     - name: Verify Linux autogen
+  #       if: matrix.backend == 'amd'
+  #       run: |
+  #         cp tinygrad/runtime/autogen/libc.py /tmp/libc.py.bak
+  #         cp tinygrad/runtime/autogen/io_uring.py /tmp/io_uring.py.bak
+  #         ./autogen_stubs.sh libc
+  #         ./autogen_stubs.sh io_uring
+  #         diff /tmp/libc.py.bak tinygrad/runtime/autogen/libc.py
+  #         diff /tmp/io_uring.py.bak tinygrad/runtime/autogen/io_uring.py
+  #     - name: Run pytest (not cuda or amd)
+  #       if: matrix.backend!='ptx' && matrix.backend!='triton' && matrix.backend != 'amd' && matrix.backend != 'nv'
+  #       run: python -m pytest -n=auto test/ --ignore=test/unit --durations=20
+  #     # - name: Run test_ops with FUZZ_UOPS=1
+  #     #   if: matrix.backend!='cuda' && matrix.backend!='ptx' && matrix.backend!='triton' && matrix.backend != 'amd' && matrix.backend != 'nv'
+  #     #   run: FUZZ_UOPS=1 python -m pytest -n=auto test/test_ops.py --durations=20
+  #     - name: Run ONNX (only LLVM)
+  #       if: matrix.backend == 'llvm'
+  #       run: python -m pytest -n=auto test/external/external_test_onnx_backend.py --durations=20
+  #     - name: Run pytest (cuda)
+  #       if: matrix.backend=='ptx'||matrix.backend=='triton'||matrix.backend=='nv'
+  #       run: python -m pytest -n=auto test/ -k 'not (half or test_efficientnet_safetensors)' --ignore=test/external --ignore=test/models --ignore=test/unit --ignore test/test_gc.py --durations=20
+  #     - name: Run pytest (amd)
+  #       if: matrix.backend=='amd'
+  #       run: python -m pytest -n=auto test/test_ops.py test/test_dtype.py test/test_dtype_alu.py test/test_linearizer.py test/test_randomness.py test/imported/test_indexing.py test/test_hcq.py --durations=20
+  #     - name: Run TRANSCENDENTAL math
+  #       run: TRANSCENDENTAL=2 python -m pytest -n=auto test/test_ops.py::TestOps::test_sin test/test_ops.py::TestOps::test_cos test/test_ops.py::TestOps::test_tan test/test_ops.py::TestOps::test_exp test/test_ops.py::TestOps::test_log --durations=20
+  #     - name: Run process replay tests
+  #       run: |
+  #         export PR_TITLE=$(jq -r .pull_request.title "$GITHUB_EVENT_PATH")
+  #         export COMMIT_MESSAGE=$(git show -s --format=%B ${{ github.event.pull_request.head.sha }})
+  #         cp test/external/process_replay/process_replay.py ./process_replay.py && git fetch origin master && git -c advice.detachedHead=false checkout origin/master && PYTHONPATH=. python3 process_replay.py
 
   #testunicorn:
   #  name: ARM64 unicorn Test
